"""add user relation to jobs

Revision ID: 90fa4742095d
Revises: 2db218faa78f
Create Date: 2026-08-07 17:50:53.789959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fa4742095d'
down_revision: Union[str, Sequence[str], None] = '2db218faa78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
